### ISSUE TITLE
CodeMirror text editor on https://drawshield.net/create/index.html has too low height

### ISSUE THREAD

**Issue by Anthony-Gaudino** [karlwilcox/Drawshield-Code#1]
While visiting your website I noticed that on the page https://drawshield.net/create/index.html, there should appear a CodeMirror text editor, but it's height is set too low, only `3px`.

```html
<div class="CodeMirror cm-s-default CodeMirror-wrap CodeMirror-empty" style="height: 3px;">...</div>
```

I tested it on Firefox 52.8.0.

**Comment by karlwilcox** [comment]
Thanks for getting in touch Anthony - that is possibly a CodeMirror problem with an older version of Firefox. The source HTML is an ordinary &lt;textarea> element, I just load a local copy of the CodeMirror Javascript and call it with the textarea as argument, that does all the div creation. It seems to work fine on Firefox 61.0.1 on my Mac (see screenshot below), but I do notice that the version of CodeMirror I use is out of date (5.33.0 vs 5.39.2) so I will update it on my test server and if it looks OK I will promote it to the live system and report back here just in case that is the problem. I'll be in touch.

<img width="757" alt="image" src="https://user-images.githubusercontent.com/3171760/43025326-3707a1fe-8c69-11e8-9347-cf44f326ee9c.png">

**Comment by karlwilcox** [comment]
Code mirror upgraded to 5.33. Please let me know if the problem re-occurs.

**Comment by Anthony-Gaudino** [comment]
Sorry @karlwilcox, but it still seems to have the same problem on https://drawshield.net.
![drawshield_codemirror_bug](https://user-images.githubusercontent.com/2439728/44299058-f8823880-a2ee-11e8-9690-f656f9981161.png)

On this page: https://codemirror.net/demo/resize.html CodeMirror works fine on my browser.

I don't know what it could be because I don't have experience with CodeMirror, but one option to solve the problem could be to just remove any inline style from the div after the page is fully loaded, this way the `height: 3px;` wouldn't cause problems. Another option would be to add `height: auto !important;` to CSS.
