### ISSUE TITLE
In Annulo arrangement

### ISSUE THREAD

**Issue by karlwilcox** [karlwilcox/Drawshield-Code#2]
Add the arrangement "in annulo" - user suggestion

I have sketched out the algorithm for this, I just need to implement it

**Comment by zifyoip** [comment]
I think this is done—at least "in annulo" seems to work in all cases I've tried. Is there more to do?

Azure, twelve mullets in annulo or.
![Azure, twelve mullets in annulo or](https://user-images.githubusercontent.com/62176468/78939305-2c0d6a00-7ab4-11ea-9ffd-701970e0ff9c.png)

**Comment by karlwilcox** [comment]
Yes, it is all done. This issues list is quite out of date, I moved to a trello board `https://trello.com/b/3gZPyGW7/drawshieldnet` as that seemed more flexible and gave more visibility (and there were no other Github contributors at the time). The trello board is probably a bit out of date too... I’ll spend a bit of time consolidating everything I have here... Watch this space!
